[tool.poetry]
name = "gimer"
version = "0.1.0"
description = "Gitのマージを楽にするCLIツール"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "gimer"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.2.1"
gitpython = "^3.1.44"
rich = "^14.0.0"

[tool.poetry.scripts]
gimer = "gimer.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
