name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest
    
    - name: Install dependencies
      run: uv sync --all-extras
    
    - name: Build package
      run: uv build
    
    - name: Build binary
      run: uv run pyinstaller gimer.spec
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: dist/*.whl
    
    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: dist/gimer

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download package artifacts
      uses: actions/download-artifact@v4
      with:
        name: package
        path: dist/
    
    - name: Download binary artifacts
      uses: actions/download-artifact@v4
      with:
        name: binary
        path: dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/gimer
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
